[package]
name = "library"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
filetime.workspace = true
chrono.workspace = true
string_py ="0.2.0"
encoding_rs = "0.8.33"
rust-ini = "0.21"
local-ip-address = "0.6.1"
