[package]
name = "para_porter_server"
version = "0.1.0"
edition = "2021"

[dependencies]
library = {path = "../library" }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
string_py.workspace = true
actix-web = "4"
anyhow = "1.0.81"
