[package]
name = "para_porter_client"
version = "0.1.0"
edition = "2021"

[dependencies]
library = {path = "../library"}
serde ={ workspace=true}
serde_json ={ workspace=true }
reqwest = { version = "0.11.26", features = ["json"] }
tokio = { version = "1.36.0", features = ["full"] }
